### ISSUE TITLE
Upsert passes arguments to jsforce in incorrect order

### ISSUE THREAD

**Issue by stuartc** [OpenFn/language-salesforce#1]

**Comment by taylordowns2000** [comment]
Hey @stuartc , this seems to have come back (????) and is presenting issues for all MyAgro upserts. Very strange. See below for examples where the external ID is definitely provided, but jsForce tells us it isn't:
```
Logging in as myagro@vera.org.
Upserting Packet__c with externalId Grand_Packet_extID__c : { Grand_Packet_extID__c: 'SMSTO:+22394806941:paquet 1420',
  Date_Received__c: '2016-01-09T13:22:11.903000',
  Zone__r: { Zone_Code__c: 'a2Fb00000005Twm' } }
[Error: External ID is not defined in the record]
Error: External ID is not defined in the record
    at /app/node_modules/jsforce/lib/connection.js:739:31
    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)
    at Connection.upsert (/app/node_modules/jsforce/lib/connection.js:735:7)
    at /app/node_modules/language-salesforce/lib/Adaptor.js:138:21
    at wrapper (/app/node_modules/lodash-compat/index.js:3670:19)
    at /app/node_modules/promise/lib/core.js:33:15
    at flush (/app/node_modules/asap/asap.js:27:13)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
Job failed.
```
Similarly:
```
Logging in as myagro@vera.org.
Upserting Packet__c with externalId Grand_Packet_extID__c : { name: 'SMSTO:+22394806941:paquet 1419',
  Grand_Packet_extID__c: 'SMSTO:+22394806941:paquet 1419' }
[Error: External ID is not defined in the record]
Error: External ID is not defined in the record
    at /app/node_modules/jsforce/lib/connection.js:739:31
    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)
    at Connection.upsert (/app/node_modules/jsforce/lib/connection.js:735:7)
    at /app/node_modules/language-salesforce/lib/Adaptor.js:138:21
    at wrapper (/app/node_modules/lodash-compat/index.js:3670:19)
    at /app/node_modules/promise/lib/core.js:33:15
    at flush (/app/node_modules/asap/asap.js:27:13)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
Job failed.
```
